#!/usr/bin/env bash
# Build a Linux toolchain that can produce NEW-ABI arm64e, for the modern
# lanes (rootful-modern, rootless, roothide).
#
# Why this exists: arm64e slices carry a capability field in cpusubtype (xnu
# osfmk/mach/machine.h) -- bit 31, CPU_SUBTYPE_PTRAUTH_ABI, marks the versioned
# ABI, with the version in bits 24-27. Theos's bundled Linux clang compiles
# arm64e happily but stamps 0x00000002, the pre-Xcode-12 preview ABI that
# modern ld calls "arm64e.old" and refuses to link against. A framework built
# that way is silently wrong rather than loudly broken. Only the *compiler* is
# at fault: theos's ld64 and cctools handle the versioned ABI correctly.
#
# So this assembles a hybrid: theos's linux/iphone toolchain (ld64, cctools,
# ldid) with its compiler drivers replaced by one that emits 0x80000002.
#
#   tools/dependencies/setup-modern-toolchain.sh [CLANG]     build the toolchain
#   tools/dependencies/setup-modern-toolchain.sh --verify D  check an existing one
#
# CLANG defaults to the first candidate on PATH that passes the probe. macOS
# needs none of this -- Xcode 12+ emits the versioned ABI natively.
set -euo pipefail

: "${THEOS:?THEOS must point to Theos}"

BASE="$THEOS/toolchain/linux/iphone"
DEST="${MODERN_TOOLCHAIN:-$THEOS/toolchain/modern/linux/iphone}"

# Compile a trivial arm64e object and read the cpusubtype's capability byte.
# Byte 11 of a little-endian 64-bit Mach-O is the high byte of cpusubtype, so
# 0x80 there means CPU_SUBTYPE_PTRAUTH_ABI is set. No sysroot needed: the probe
# source includes nothing.
probe_new_abi() {
    local cc=$1 tmp cap
    [ -x "$cc" ] || return 1
    tmp=$(mktemp -d)
    trap 'rm -rf "$tmp"' RETURN
    echo 'int probe(int x){return x+1;}' > "$tmp/p.c"
    "$cc" -c -target arm64e-apple-ios14.0 -o "$tmp/p.o" "$tmp/p.c" 2>/dev/null || return 1
    cap=$(od -An -tx1 -j11 -N1 "$tmp/p.o" | tr -d ' \n')
    [ "$cap" = "80" ]
}

if [ "${1:-}" = --verify ]; then
    dir=${2:-$DEST}
    probe_new_abi "$dir/bin/clang" || {
        echo "error: $dir/bin/clang does not emit new-ABI arm64e" >&2
        exit 1
    }
    echo "OK: $dir/bin/clang emits new-ABI arm64e (cpusubtype 0x80000002)"
    exit 0
fi

[ -d "$BASE/bin" ] || { echo "error: no theos Linux toolchain at $BASE/bin" >&2; exit 1; }

CLANG=${1:-}
if [ -n "$CLANG" ]; then
    probe_new_abi "$CLANG" || { echo "error: $CLANG does not emit new-ABI arm64e" >&2; exit 1; }
else
    for c in clang clang-22 clang-21 clang-20 clang-19 clang-18; do
        p=$(command -v "$c" 2>/dev/null) || continue
        if probe_new_abi "$p"; then CLANG=$p; break; fi
    done
    [ -n "$CLANG" ] || {
        echo "error: no clang on PATH emits new-ABI arm64e" >&2
        echo "       install a newer clang and pass it explicitly" >&2
        exit 1
    }
fi

CLANG=$(readlink -f "$CLANG")
CLANG_BIN=$(dirname "$CLANG")
echo "compiler: $CLANG"
echo "base:     $BASE/bin (ld64 + cctools)"
echo "dest:     $DEST/bin"

rm -rf "$DEST"
mkdir -p "$DEST/bin"
# ld64, lipo, ar, nm, otool, ldid, ... all handle the versioned ABI fine. The
# compiler drivers are deliberately skipped: they get replaced by the wrapper
# below, and a symlink here would be a live path back into the base toolchain
# for anything that writes through it.
for f in "$BASE/bin"/*; do
    case "$(basename "$f")" in
        clang|clang++|cc|c++) continue ;;
    esac
    ln -sf "$f" "$DEST/bin/$(basename "$f")"
done

# The compiler drivers are wrapped rather than symlinked, because theos assumes
# an Apple clang in two places that a stock clang breaks:
#
#  1. darwin_tail.mk adds -fuse-ld= ONLY when the toolchain has a binary prefix.
#     This one has none, so nothing selects the linker: Apple's clang defaults
#     to ld64, but a stock clang defaults to the host ELF ld and dies with
#     "unrecognised emulation mode: llvm". Force ld64 with --ld-path=.
#  2. Where theos does pass -fuse-ld=<absolute path>, clang 12+ ignores that
#     form (superseded by --ld-path=), so it must be translated.
# rm -f first: never `>` onto a path that may still be a symlink, or the write
# follows the chain into the base toolchain and truncates the real compiler.
rm -f "$DEST/bin/clang" "$DEST/bin/clang++" "$DEST/bin/cc" "$DEST/bin/c++"
cat > "$DEST/bin/clang" <<EOF
#!/usr/bin/env bash
# Generated by tools/dependencies/setup-modern-toolchain.sh -- do not edit.
case "\$(basename "\$0")" in
    *++) REAL="$CLANG_BIN/clang++" ;;
    *)   REAL="$CLANG_BIN/clang" ;;
esac
LD="\$(dirname "\$(readlink -f "\$0")")/ld"
args=(); link=1
for a in "\$@"; do
    case "\$a" in
        -c|-E|-S|-fsyntax-only) link=0; args+=("\$a") ;;
        -fuse-ld=/*)            link=0; args+=("--ld-path=\${a#-fuse-ld=}") ;;
        *)                      args+=("\$a") ;;
    esac
done
[ "\$link" = 1 ] && args+=("--ld-path=\$LD")
exec "\$REAL" "\${args[@]}"
EOF
chmod +x "$DEST/bin/clang"
for d in clang++ cc c++; do ln -sf "$DEST/bin/clang" "$DEST/bin/$d"; done

probe_new_abi "$DEST/bin/clang" || { echo "error: assembled toolchain fails the probe" >&2; exit 1; }
echo "OK: $DEST/bin emits new-ABI arm64e"
echo "build.sh picks this up automatically; override with MODERN_TOOLCHAIN=."
